hash-format = "sha256"

[[files]]
file = "config/enchancement.json"

[[files]]
file = "config/mod-loading-screen/background.png"

[[files]]
file = "config/mod-loading-screen/config.txt"

[[files]]
file = "config/mod-loading-screen/icon.png"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"

[[files]]
file = "config/yosbr/config/carryon-common.json"

[[files]]
file = "config/yosbr/config/connectiblechains.toml"

[[files]]
file = "config/yosbr/config/endrem.json"

[[files]]
file = "config/yosbr/config/invmove/unrecognized.json"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"

[[files]]
file = "config/yosbr/config/particlerain.json5"

[[files]]
file = "config/yosbr/config/ping-wheel.json"

[[files]]
file = "config/yosbr/config/ping-wheel.server.json"

[[files]]
file = "config/yosbr/config/sit!/server-config.json"

[[files]]
file = "config/yosbr/config/valkyrienskies/vs_clockwork_server.json"

[[files]]
file = "config/yosbr/config/valkyrienskies/vs_common.json"

[[files]]
file = "config/yosbr/config/valkyrienskies/vs_core_server.json"

[[files]]
file = "config/yosbr/config/valkyrienskies/vs_eureka_server.json"

[[files]]
file = "config/yosbr/config/valkyrienskies/vs_server.json"

[[files]]
file = "config/yosbr/config/voicechat/voicechat-server.properties"

[[files]]
file = "datapacks/create-x-valkyrien-skies-clockwork-survival-support.pw.toml"
metafile = true

[[files]]
file = "mods/advancementinfo.pw.toml"
metafile = true

[[files]]
file = "mods/allow-editing-player`s-nbt!.pw.toml"
metafile = true

[[files]]
file = "mods/amarite.pw.toml"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/arsenal.pw.toml"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/axolotl-buckets.pw.toml"
metafile = true

[[files]]
file = "mods/azurelib.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/bits-and-chisels.pw.toml"
metafile = true

[[files]]
file = "mods/blahaj.pw.toml"
metafile = true

[[files]]
file = "mods/blahaj_fabric.pw.toml"
metafile = true

[[files]]
file = "mods/blast.pw.toml"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
metafile = true

[[files]]
file = "mods/bmpv.pw.toml"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/brrp.pw.toml"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/carpet-ams-addition.pw.toml"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
metafile = true

[[files]]
file = "mods/carryon-vs-compat.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cc-vs.pw.toml"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/chatshot.pw.toml"
metafile = true

[[files]]
file = "mods/chest-tracker.pw.toml"
metafile = true

[[files]]
file = "mods/chunk-debug.pw.toml"
metafile = true

[[files]]
file = "mods/chunk-loaders.pw.toml"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
metafile = true

[[files]]
file = "mods/connectiblechains.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
metafile = true

[[files]]
file = "mods/couplings.pw.toml"
metafile = true

[[files]]
file = "mods/craft-slabs-back-into-blocks.pw.toml"
metafile = true

[[files]]
file = "mods/craftsense.pw.toml"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
metafile = true

[[files]]
file = "mods/create-bitterballen.pw.toml"
metafile = true

[[files]]
file = "mods/create-broken-bad-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-clockwork.pw.toml"
metafile = true

[[files]]
file = "mods/create-cobblestone.pw.toml"
metafile = true

[[files]]
file = "mods/create-data-and-plots.pw.toml"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
metafile = true

[[files]]
file = "mods/create-deepfried.pw.toml"
metafile = true

[[files]]
file = "mods/create-enchantment-industry-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-food.pw.toml"
metafile = true

[[files]]
file = "mods/create-let-the-adventure-begin.pw.toml"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
metafile = true

[[files]]
file = "mods/create-ore-excavation.pw.toml"
metafile = true

[[files]]
file = "mods/create-renewable-egapples.pw.toml"
metafile = true

[[files]]
file = "mods/create-rustic-structures.pw.toml"
metafile = true

[[files]]
file = "mods/create-stone-generators.pw.toml"
metafile = true

[[files]]
file = "mods/create-structures-arise.pw.toml"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
metafile = true

[[files]]
file = "mods/create-totem-factory-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-track-map.pw.toml"
metafile = true

[[files]]
file = "mods/createnuclear.pw.toml"
metafile = true

[[files]]
file = "mods/createrem.pw.toml"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
metafile = true

[[files]]
file = "mods/datapacks.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/defile.pw.toml"
metafile = true

[[files]]
file = "mods/deimos.pw.toml"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
metafile = true

[[files]]
file = "mods/diagonal-walls.pw.toml"
metafile = true

[[files]]
file = "mods/diagonal-windows.pw.toml"
metafile = true

[[files]]
file = "mods/dirtnt.pw.toml"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/ducky-periphs.pw.toml"
metafile = true

[[files]]
file = "mods/easy-eula.pw.toml"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
metafile = true

[[files]]
file = "mods/effective.pw.toml"
metafile = true

[[files]]
file = "mods/elegantia.pw.toml"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
metafile = true

[[files]]
file = "mods/enchancement.pw.toml"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
metafile = true

[[files]]
file = "mods/enhanced-groups.pw.toml"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
metafile = true

[[files]]
file = "mods/escalated.pw.toml"
metafile = true

[[files]]
file = "mods/essentialclient.pw.toml"
metafile = true

[[files]]
file = "mods/estrogen.pw.toml"
metafile = true

[[files]]
file = "mods/eureka.pw.toml"
metafile = true

[[files]]
file = "mods/every-compat.pw.toml"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
metafile = true

[[files]]
file = "mods/exposure-catalog.pw.toml"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/extreme_sound_muffler.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
metafile = true

[[files]]
file = "mods/fancysporeblossom.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-knives.pw.toml"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/figura-goofyplugin.pw.toml"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
metafile = true

[[files]]
file = "mods/figurasvc.pw.toml"
metafile = true

[[files]]
file = "mods/firework-frenzy.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/grappling-hook-mod-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/gravestones.pw.toml"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-melodies.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-winds.pw.toml"
metafile = true

[[files]]
file = "mods/immersivethunder.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/ingamestats.pw.toml"
metafile = true

[[files]]
file = "mods/interactive.pw.toml"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/item-despawn-timer.pw.toml"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
metafile = true

[[files]]
file = "mods/itemflexer.pw.toml"
metafile = true

[[files]]
file = "mods/itemphysic.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/jade-vs.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/keybind-fix.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/leashable-collars.pw.toml"
metafile = true

[[files]]
file = "mods/lexiconfig.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lodentityrendering.pw.toml"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
metafile = true

[[files]]
file = "mods/mcpitanlibarch.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
metafile = true

[[files]]
file = "mods/mirage_mod.pw.toml"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
metafile = true

[[files]]
file = "mods/mod-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu-command.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/mystical-oak-tree.pw.toml"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
metafile = true

[[files]]
file = "mods/next-fabric-bedrock-miner.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
metafile = true

[[files]]
file = "mods/omnilib.pw.toml"
metafile = true

[[files]]
file = "mods/opac-fabric-create-support.pw.toml"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
metafile = true

[[files]]
file = "mods/openpac-bluemap-remapped.pw.toml"
metafile = true

[[files]]
file = "mods/oplock.pw.toml"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/pick-your-poison.pw.toml"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/ratatouille.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled-create.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/remember-my-txt.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/respawnable-pets.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
metafile = true

[[files]]
file = "mods/simple-uncrafting-table.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/sit!.pw.toml"
metafile = true

[[files]]
file = "mods/sneaky-server.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/sparkweave.pw.toml"
metafile = true

[[files]]
file = "mods/sph.pw.toml"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/stone-zone.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/tiny-coal.pw.toml"
metafile = true

[[files]]
file = "mods/tiny-item-animations.pw.toml"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
metafile = true

[[files]]
file = "mods/tp-utils.pw.toml"
metafile = true

[[files]]
file = "mods/trackwork-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
metafile = true

[[files]]
file = "mods/undefile.pw.toml"
metafile = true

[[files]]
file = "mods/usage-ticker.pw.toml"
metafile = true

[[files]]
file = "mods/valkib.pw.toml"
metafile = true

[[files]]
file = "mods/valkyrien-engines.pw.toml"
metafile = true

[[files]]
file = "mods/valkyrien-pirates.pw.toml"
metafile = true

[[files]]
file = "mods/valkyrien-relogs.pw.toml"
metafile = true

[[files]]
file = "mods/valkyrien-skies-2-+-supplementaries-cannon-fix.pw.toml"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
metafile = true

[[files]]
file = "mods/vlib.pw.toml"
metafile = true

[[files]]
file = "mods/vmod.pw.toml"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
metafile = true

[[files]]
file = "mods/vs-grapples.pw.toml"
metafile = true

[[files]]
file = "mods/vs-tournament.pw.toml"
metafile = true

[[files]]
file = "mods/way2wayfabric.pw.toml"
metafile = true

[[files]]
file = "mods/wearthat.pw.toml"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
metafile = true

[[files]]
file = "mods/windchimes.pw.toml"
metafile = true

[[files]]
file = "mods/wnt.pw.toml"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
metafile = true

[[files]]
file = "mods/worldeditcui-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/xaero-zoomout.pw.toml"
metafile = true

[[files]]
file = "mods/xaeroplus.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true

[[files]]
file = "mods/your-reputation.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true

[[files]]
file = "unsup.ini"
