name = "Gambling Addict Manufacturing Pack"
author = "nemmy"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcc40566d9aedd8898dc17a63ff0ca211e828cfa6a4faacb266a69ccdd0db273"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
