name = "Gambling Addict Manufacturing Pack"
author = "nemmy"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9bb09fdbbcf820397aae0f798c4744671cdb685ae9a06951315ea4cf34e09c0"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
