name = "Gambling Addict Manufacturing Pack"
author = "nemmy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3babe34fce33edb270f93980e517243cf084138cca88978d9bd08a55bf4d38c"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
