name = "Gambling Addict Manufacturing Pack"
author = "nemmy"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "026a5ec0eeb8129aa9f74a1b679366e626098892a7712d39fdfbec9dd94aee7c"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
